export const GAME_MAP_PENDING = 'GAME_MAP_PENDING';
export const GAME_MAP_FULFILLED = 'GAME_MAP_FULFILLED';
export const GAME_MAP_REJECTED = 'GAME_MAP_REJECTED';

export const GAME_LIST_PENDING = 'GAME_LIST_PENDING';
export const GAME_LIST_FULFILLED = 'GAME_LIST_FULFILLED';
export const GAME_LIST_REJECTED = 'GAME_LIST_REJECTED';

export const VALIDATE_MOVE_RESULT_PENDING = 'VALIDATE_MOVE_RESULT_PENDING';
export const VALIDATE_MOVE_RESULT_FULFILLED = 'VALIDATE_MOVE_RESULT_FULFILLED';
export const VALIDATE_MOVE_RESULT_REJECTED = 'VALIDATE_MOVE_RESULT_REJECTED';

export const INITIAL_MAP_PENDING = 'INITIAL_MAP_PENDING';
export const INITIAL_MAP_FULFILLED = 'INITIAL_MAP_FULFILLED';
export const INITIAL_MAP_REJECTED = 'INITIAL_MAP_REJECTED';

export const SAVE_MAP_PENDING = 'SAVE_MAP_PENDING';
export const SAVE_MAP_FULFILLED = 'SAVE_MAP_FULFILLED';
export const SAVE_MAP_REJECTED = 'SAVE_MAP_REJECTED';

export const HINT_MOVE_PENDING = 'HINT_MOVE_PENDING';
export const HINT_MOVE_FULFILLED = 'HINT_MOVE_FULFILLED';
export const HINT_MOVE_REJECTED = 'HINT_MOVE_REJECTED';
